### PR TITLE
Doc updates for 2.0.

### PR DESCRIPTION
**Pull request by jrochkind**
Not sure why I had to re-apply the changes to doc/settings.md
that should have been merged in #74

### CODE REVIEW

**Comment by jrochkind** [comment]
Hey @billdueber , can I merge my doc updates? Feel like reviewing them?

**Comment by billdueber** [comment]
Only comment: I'm pretty sure the marc4j reader is gobs faster when pulling in XML, which would be a good reason to use it over ruby-marc. I'll run a quick benchmark. Otherwise, looks great; go ahead and merge it if you're happy, and I'll amend that particular line if need be.

**Comment by billdueber** [comment]
Yeah, marc4j is about twice as fast.

https://gist.github.com/billdueber/a388b2d0d3aec7f96134

Of course, I have no idea how much of a factor that is for a regular indexing job (i.e., to what extent is parsing speed subsumed by indexing speed?)

**Comment by jrochkind** [comment]
Crap. The only reason I was okay with pulling marc4j out entirely was because I was under the misimpression that it was NOT faster, that we had verified it was no faster. 

Hmm, now I don't know what to do. I kind of want traject to use marc4j reader by default on jruby now. Any ideas of the best way to make that happen?  I'm not sure. 

In the meantime, want to adjust the docs to be accurate in my PR? merge first then adjust?

**Comment by billdueber** [comment]
Merge first. I'll see if I can get some idea of the effect on a real indexing job before we worry about it too much.

**Comment by jrochkind** [comment]
Bah, it's not mergable now because of changes made since I filed the PR. I'll try to rebase and resolve I guess, sorry might not get to it right away. 

We should probably merge dev-2.0 to master before cutting a 2.0-rc1. whcih is inconvenient with outstanding PR's against dev-2.0.  @barmintor seems to be in a hurry to get a 2.0.rc1, I guess we could release it off the dev-2.0 branch too, that's not really a problem.

**Comment by billdueber** [comment]
@barmintor, was your deadline for really wanting a release the c4l preconf? If so, then we can give ourselves a breathing minute, because we already missed his deadline.

**Comment by billdueber** [comment]
OK, so doing my normal indexing (minus the database calls, which most folks won't do) against 150k binary marc records and writing to the null writer shows marc4j speeding this up by about a third. This is something I never look at because I use alephsequential and ndj files.

Using the JSON writer, to get a more (but not totally) realistic writing load, gives marc4j a 20% speed advantage. I imagine it would be similar with xml, and similar when writing to solr. 

Personally, I think the solution is to just document it. We could even throw up a warning in the logfile in the vein of the current "you're using MRI and that's not great" -- "You're using JRuby with the Traject::MarcReader. You will likely get substantial speedups if you install and use traject-marc4j_reader"

**Comment by barmintor** [comment]
Yeah, breathe easier. I'll probably push a version pinned to the commit ref.

**Pull request merged**
