### PR TITLE
Batch solr json writer

### PR DESCRIPTION
**Pull request by billdueber**
Replace `solr_json_writer` with a batched version.

Changes:
  * move old `solr_json_writer` to `nobatch_solr_json_writer`
  * Allow explicit update url vial setting `solr.update_url`
  * If only `solr.url` is present, sniff out whether to send to `/update/json` or just `/update`
  * use of new class `Traject::AllRubyThreadPool` under MRI (by @jrochkind)
  * use of new class `Traject::Queue` under MRI (wanted a safe `#drain_to`)
  * use `Concurrent::AtomicFixed` under both (on JRuby, it falls back to the same java.util.concurrent class we were using before, so no performance loss)

Not at all sure how to test any of this. 

* [x] Remove Traject::Queue, make a Traject.drain_queue utility method that can drain a stdlib queue, just use stdlib queues. 

* [x] Review/Improve error capturing/reporting

* [x] Remove nonbatch_solr_json_writer.rb, it's been replaced by the solr_json_writer.rb with batching

* [x] Remove Traject::AllRubyThreadPool as a separate implementation, use it's implementation as new Traject::ThreadPool

* [x] solrj_writer.commit_on_close also honored, so people upgrading and using default writer
       will not unexpectedly find no commits happening. 

* [x] Investigate binary marc issue. Using SolrJ, I'm doing something not technically right but works in storing binary marc in Solr -- something inherited from SolrMarc, which a lot of other people are probably doing too. I suspect that something will not work with this approach -- need to investigate to be sure, document and/or make it work, and for myself switch to storing binary marc in an actually supported way and/or stop using binary marc.  (resolved: not-quite-supported binary adds end up working the same here as they did with SolrJWriter)

* [x] Investigate possible bug or unexpected behavior in Concurrent::ThreadPoolExecutor. https://github.com/traject-project/traject/blob/5d507bc93b67bf8271279d495b811d462d829099/test/solr_json_writer_test.rb#L138 (Resolved: SolrJsonWriter#close was not using the threadpool, leading to non-deterministic order of adds. Which may not really matter, but I changed it to use thread pool as SolrJWriter did, leading to deterministic ordering of adds in tests)

### CODE REVIEW

**Comment by jrochkind** [comment]
Added a checklist of things to do. I plan to do em. Should have some time next week.

**Comment by jrochkind** [comment]
I noticed the thread pool size is defaulting to 0, not 1. And in fact, the tests I initially wrote don't seem to pass when I make it properly default to 1!  I'll look into it. 

(Note: `defined? nil` is evaluated as true in a boolean context.  `defined?` is just for checking for variables that literally have not been assigned anything, assigned nil is defined).

**Comment by jrochkind** [comment]
Although, @billdueber , if it was defaulting to 0 threads before, and you were still seeing great performance -- I wonder if that means we don't need the threads at all, which would simplify implementation. Still, a background thread seems like it should help, so I'll fix it anyhow!

**Comment by billdueber** [comment]
The thread size was set to zero because I was testing under MRI, and then I must've forgot about it. Are the tests all passing now?

Performance benchmarking was between single-threaded solrj and single-threaded solr-json, in which the latter came in about 20% faster. Multiple cores don't scale linearly, but they do way better than that.

**Comment by jrochkind** [comment]
Reviewed and reworked the error handling -- with some tests. 

I realized even the older SolrJWriter had kind of messed up error handling. I made some different choices than you did in trying to make things work right -- I made the DEFAULT_MAX_SKIPPED 0 for now, will raise on 1 skipped record. Personally, in production, I want an abort and failure if even a single record can't be added. 

All of the choices can be changed if deemed neccesary from experience, of course.

**Comment by billdueber** [comment]
​That's fine with me. As a point of reference, I go totally teh other way.
If I'm 9M records in and something goes weird because I didn't deal with a
short 008 or something, I'd rather get the error log and fix it
record-by-record. A few bad records won't keep me from releasing a new
index, but an incomplete index will. ​

On Tue, Jan 13, 2015 at 1:06 PM, Jonathan Rochkind <notifications@github.com
> wrote:

> Reviewed and reworked the error handling -- with some tests.
>
> I realized even the older SolrJWriter had kind of messed up error
> handling. I made some different choices than you did in trying to make
> things work right -- I made the DEFAULT_MAX_SKIPPED 0 for now, will raise
> on 1 skipped record. Personally, in production, I want an abort and failure
> if even a single record can't be added.
>
> All of the choices can be changed if deemed neccesary from experience, of
> course.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/traject-project/traject/pull/63#issuecomment-69789757>
> .
>



-- 
Bill Dueber
Library Systems Programmer
University of Michigan Library

**Comment by jrochkind** [comment]
If we think most people are like you, we can change the default before release. The functionality is there either way. 

As far as your previous question about default threads: it actually was a bug that it was defaulting to 0 I think, the logic for applying the default wasn't right. Fixed, with test.  

And the tests not passing were just tests I wrote -- and actually make me suspicious of a bug in Concurrent::ThreadPoolExecutor, things were happening in a different order than I expect, and I'm not sure why, and I want to investigate that too. 

Moving along. I'm very excited to have a traject release with NO jruby dependencies in sight. Thanks for pushing for that (when I was initially skeptical) and working on it with me!

**Comment by jrochkind** [comment]
Oh, and the potential perf improvement of a threads in SolrJsonWriter is, to me, less about cores -- it's becuase the SolrJsonWriter thread will spend some time waiting on an HTTP response from Solr, and by putting it it's own thread, when it's doing that waiting, traject can keep processing records on other threads, even with only one core.

**Comment by jrochkind** [comment]
ready for merge as far as i'm concerned!

**Comment by billdueber** [comment]
Just a couple comments/questions:

* What's the point of [being able to pass in an http client](https://github.com/traject-project/traject/compare/eb6e99da3838416e0fd612a32dfa0a68200ec4d6...batch_solr_json_writer#diff-d6f8e4e7c27247af134c26e2a55a11c3R69)? Just so we don't have more than one floating around if you choose to pass in an HTTPClient object from the outside? It would have to be an HTTPClient object; we're relying on its specific interface. Or is it just for DI when testing?
* Is the purpose of explicitly using a block arg [here](https://github.com/traject-project/traject/compare/eb6e99da3838416e0fd612a32dfa0a68200ec4d6...batch_solr_json_writer#diff-d6f8e4e7c27247af134c26e2a55a11c3R105) to make sure the batch queue doesn't somehow disappear between threaded calls? Just wondering.

Looks great! I'm going to test and maybe benchmark today.

**Comment by atz** [comment]
Passing in a client is common to account for all the crappy preconfigurations that one might have to apply: certs, keys, SSL config, kerberos, proxy, max redirects, whitelist/blacklist, security zones, timeouts, logging, session initialization, etc.  The configuration and spin-up cost can be significant.  I'm guessing that is the reason here also.

**Comment by jrochkind** [comment]
Actually, the only point I had in being able to pass in an HTTPClient was to accomodate testing -- in testing, I pass in a mock/double client, so I can capture the HTTP requests and see what they were, without them being sent to a live server. 

That was my only motivation, although it's possible people could find other uses for it, they are a bit 'risky' as far as forwards-compat, if we changed our implementation to use some other gem than http_client, they could break. 

The docs for that setting at the top of the source file say:

> # * solr_json_writer.http_client Mainly intended for testing, set your own HTTPClient
> #   or mock object to be used for HTTP.

**Comment by jrochkind** [comment]
Re the argument on the threading call [here](https://github.com/traject-project/traject/compare/eb6e99da3838416e0fd612a32dfa0a68200ec4d6...batch_solr_json_writer#diff-d6f8e4e7c27247af134c26e2a55a11c3R105), that was the very last commit I made. 

The purpose is multi-threading is hard, and I'm scared of this, check this out:

~~~ruby
x = 100
t = Thread.new do
   sleep 4
   puts x
end
x = 400

t.join
~~~

Will put 400.  It's a "live" variable -- in our code, if the loop comes around again before the block has finished executing in the thread, the value of the `batch` local variable will change right out from under it. Which could conceivably cause some records to be skipped (the same `batch` could be added twice), and nobody would be the wiser. 

The SolrJWriter was subject to this too. I think it's probably very unlikely and perhaps impossible. But while trying to debug something _else_ I was having trouble debugging, I considered this issue -- the something else ended up not being related to this. But having become aware of it, I got nervous. 

Interestingly/scarily, this would be another way hypothetically to solve the problem:

~~~ruby
@thread_pool.maybe_in_thread_poo  do 
    batch = Traject::Util.drain_queue(@batched_queue)
    send_batch(batch_arg) }
end
~~~

That even seems preferable, right? When I tried that -- my tests deadlocked!  I have no idea why, it doesn't make any sense, there should be no deadlock possible there, it makes me nervous. But I gave up, and realized the block thing can solve it, so good enough.  Ruby stdlib `Thread.new(x) do |local_x| ` is meant to handle this problem, and that's what we're using.

**Comment by billdueber** [comment]
Just ran a quick benchmark indexing from my desktop (less-than-ideal) to an actual solr server (ideal). 

Numbers are as reported the in traject log against a file of 200k marc-in-json records using my standard indexing.

## Overall speed for 200k records

Average of three runs set for 3 indexing threads and one solr thread; **higher is better**

Platform/Indexer| solr_json (rec/s) | solrj (rec/s)
-------------------------|---:|---:|
mri 2.2 | 353 | N/A 
jruby 1.7.18 | 443 | 415
 

## First 50K records

For just the first 50,000 records, for when you have a small run.

Platform/Indexer| solr_json (rec/s) | solrj (rec/s)
-------------------------|---:|---:|
mri 2.2 | 301 | N/A 
jruby 1.7.18 | 251 | 244

Obviously, it takes a while for the jruby code to warm up. 

Nothing earth-shattering here, but worth noting that:
* jruby takes quite a while to JIT; in previous runs, about 200K records to reach peak speed.
* MRI is a fair bit faster for short runs (but it's 2.5 vs. 3.5 minutes for the 50K, so who cares)
* solr_json is consistently faster than solrj for my stuff

**Comment by jrochkind** [comment]
Thanks Bill! I'm confused what those benchmarks mean. Personally, I am completely uninterested in MRI vs Jruby.  I _know_ that MRI is going to be slower just because we can't use parallelism in indexing under MRI.  Regardless of anything else, that along means use Jruby if you want high performance for a high volume of records. 

What I'm concerned with is is the performance of "traject 2.0" with the thread pool based on ruby-concurrent and the SolrJsonWriter, vs traject 1.x with the direct-jruby threadpool and the SolrJWriter. My concern is that traject 2.0 with SolrJsonWriter not be significantly less performant *under jruby* than traject 1.x with SolrJWriter (which only supported jruby). 

Have you compared that? Are you interested in doing so?

Incidentally, my test run of my entire 3 million record db using "traject 2.0" completed succesfully -- it also succesfully recovered from a timeout when talking to Solr, by resorting to individually adding docs after the timeout on `batch_add` (the timeout did not reoccur on individual add, becuase it was transient), which routinely happens in my traject 1.x executions too. Great!

**Comment by jrochkind** [comment]
Ah wait,i see the column headings now!

So it appears SolrJsonWriter is about the same speed, or even slightly faster, than SolrJWriter. Great! So all signals are green!

**Comment by billdueber** [comment]
Right. solr_json faster than solrj.

Also, jruby faster than mri by about 15% in single threaded performance, which you don't care about but other folks will.

**Comment by jrochkind** [comment]
woohoo!

After we extract SolrJ entirely, and review docs, comments, default values, utility functions, etc., to make them correctly reflect a post-SolrJ traject world.... I think we're ready for a traject 2.0 release? Maybe a 2.0.rc1 that me and you run in production for a week or so before 2.0 final. 

Looks like you already added MRI in travis?  We could add rbx too just for the heck of it, no reason this shouldn't work on rbx too (with true parallelism and no GIL), now that we're using ruby-concurrent (which specifically includes rbx in it's targets).

**Pull request merged**
